site_name: yarllib
repo_name: 'marcofavorito/yarllib'
repo_url: https://github.com/marcofavorito/yarllib

nav:
- Home: index.md
- Quickstart: "quickstart.ipynb"
- Authors: authors.md
- How to contribute: contributing.md
- How to contribute: history.md
- References: references.md


plugins:
- mknotebooks:
    execute: false
    write_markdown: false
    #preamble: ""
    #enable_default_jupyter_cell_styling: false
    #enable_default_pandas_dataframe_styling: false
- search
- bibtex:
    bib_file: "docs/refs.bib"
    cite_style: "pandoc"
    full_bib_page: "../references"

theme:
  name: material

markdown_extensions:
- codehilite
- pymdownx.arithmatex
- markdown_include.include:
    base_path: docs

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
